"use client";

import { useRef, useState } from "react";
import type { ChangeEvent } from "react";

type Signature = { cloud_name: string; api_key: string; timestamp: number; folder: string; signature: string };

export function MediaUpload({ name, label, defaultValue = "", folder = "khadeeja/content" }: { name: string; label: string; defaultValue?: string; folder?: "khadeeja/products"|"khadeeja/hero"|"khadeeja/content"|"khadeeja/instagram" }) {
  const [value,setValue]=useState(defaultValue);
  const [status,setStatus]=useState("");
  const inputRef=useRef<HTMLInputElement>(null);
  async function upload(event:ChangeEvent<HTMLInputElement>){const file=event.target.files?.[0];if(!file)return;const extension=file.name.split(".").pop()?.toLowerCase()||"";const resourceType=file.type.startsWith("video/")?"video":"image";setStatus("Preparing upload…");try{const signatureResponse=await fetch("/api/admin/media/signature",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({folder,resourceType,format:extension,fileSize:file.size})});const signature=await signatureResponse.json() as Signature&{error?:string};if(!signatureResponse.ok)throw new Error(signature.error||"Upload is unavailable.");const payload=new FormData();payload.set("file",file);payload.set("api_key",signature.api_key);payload.set("timestamp",String(signature.timestamp));payload.set("folder",signature.folder);payload.set("signature",signature.signature);const response=await fetch(`https://api.cloudinary.com/v1_1/${encodeURIComponent(signature.cloud_name)}/${resourceType}/upload`,{method:"POST",body:payload});const result=await response.json() as {secure_url?:string;error?:{message?:string}};if(!response.ok||!result.secure_url)throw new Error(result.error?.message||"Upload failed.");setValue(result.secure_url);setStatus("Upload complete.");}catch(error){setStatus(error instanceof Error?error.message:"Upload failed.");}finally{if(inputRef.current)inputRef.current.value="";}}
  return <div><label htmlFor={`${name}-url`} className="text-sm font-medium text-stone-700">{label}</label><div className="mt-1 flex flex-col gap-2 sm:flex-row"><input id={`${name}-url`} name={name} value={value} onChange={event=>setValue(event.target.value)} placeholder="/assets/... or uploaded URL" className="min-h-11 flex-1 rounded-lg border border-stone-300 bg-white px-3 text-sm outline-none focus:border-[#9c5247] focus:ring-2 focus:ring-[#9c5247]/20"/><label className="inline-flex min-h-11 cursor-pointer items-center justify-center rounded-lg border border-stone-300 bg-white px-4 text-sm font-semibold text-stone-700 hover:bg-stone-50">Upload<input ref={inputRef} type="file" accept="image/jpeg,image/png,image/webp,image/avif,video/mp4,video/webm,video/quicktime" onChange={upload} className="sr-only"/></label></div>{status?<p className="mt-1 text-xs text-stone-500" role="status">{status}</p>:null}</div>;
}
