import type { Metadata } from "next";
import { notFound } from "next/navigation";
import Link from "next/link";
import Image from "next/image";
import { Container } from "@/components/ui/Container";
import { ProductGrid } from "@/components/ui/ProductGrid";
import { ProductActions } from "@/components/product/ProductActions";
import { getDataProvider } from "@/lib/data";
import { toStorefrontProduct } from "@/lib/storefront/adapters";
import { formatPrice } from "@/lib/utils";
interface PageProps{params:Promise<{slug:string}>}
export const dynamic="force-dynamic";
export async function generateMetadata({params}:PageProps):Promise<Metadata>{const {slug}=await params;const record=await getDataProvider().getProduct(slug);if(!record)return{title:"Product Not Found"};return{title:record.seo?.title||record.name,description:record.seo?.description||record.description||undefined}}
export default async function ProductPage({params}:PageProps){const {slug}=await params;const provider=getDataProvider();const record=await provider.getProduct(slug);if(!record||record.active===false)notFound();const product=toStorefrontProduct(record);const related=(await provider.listProducts({active:true})).filter(p=>p.id!==record.id&&(p.collectionSlug===record.collectionSlug||p.categorySlug===record.categorySlug)).slice(0,4).map(toStorefrontProduct);return <div className="py-8 md:py-12"><Container><nav className="mb-8 flex items-center gap-2 text-xs text-muted" aria-label="Breadcrumb"><Link href="/">Home</Link><span>/</span><Link href="/shop">Shop</Link><span>/</span><Link href={`/collections/${product.collection}`}>{product.collection.replace(/-/g," ")}</Link><span>/</span><span className="text-ink">{product.name}</span></nav><div className="grid gap-8 md:grid-cols-2 md:gap-12"><div className="flex flex-col gap-4">{product.images.map((image,index)=><div key={`${image}-${index}`} className="relative aspect-product overflow-hidden bg-surface"><Image src={image} alt={`${product.name}${index?` view ${index+1}`:""}`} fill sizes="(max-width: 768px) 100vw, 50vw" className="object-cover" priority={index===0}/></div>)}{product.video?<div className="relative aspect-product overflow-hidden bg-surface"><video src={product.video} poster={product.images[0]} controls muted playsInline className="h-full w-full object-cover" aria-label={`Video of ${product.name}`}/></div>:null}</div><div className="flex flex-col gap-6"><div className="flex flex-col gap-2"><span className="text-xs uppercase tracking-wide text-muted">{product.category.replace(/-/g," ")}</span><h1 className="text-h1 leading-tight text-ink">{product.name}</h1><div className="flex items-center gap-2"><span className="text-xl font-medium text-ink">{formatPrice(product.price,product.currency)}</span>{product.priceStatus==="demo"?<span className="text-xs text-muted">(Demo price — subject to change)</span>:null}</div></div><p className="leading-relaxed text-muted">{product.description}</p><ProductActions product={product}/><div className="flex flex-wrap gap-2">{product.tags.map(tag=><span key={tag} className="border border-border px-3 py-1 text-xs text-muted">{tag}</span>)}</div>{record.information?<dl className="space-y-4 border-t border-border pt-6 text-sm">{[["Fabric",record.information.fabric],["Fit",record.information.fit],["Care",record.information.care],["Shipping",record.information.shipping]].filter(([,value])=>value).map(([label,value])=><div key={label}><dt className="font-semibold text-ink">{label}</dt><dd className="mt-1 text-muted">{value}</dd></div>)}</dl>:null}</div></div>{related.length?<div className="mt-20"><h2 className="mb-8 text-h2">You may also like</h2><ProductGrid products={related} columns={4}/></div>:null}</Container></div>}
